apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: image-registry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0" # allow large image uploads
spec:
  ingressClassName: nginx
  rules:
  - host: registry.kube.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: registry
            port:
              number: 5000
  tls: # Add this section
  - hosts:
    - registry.kube.lan
    secretName: registry-tls-secret # Name of the secret you created
